import fs from 'fs'
import path from 'path'

const agentsDir = path.resolve(import.meta.dirname, '..', 'agents')
const outFile = path.resolve(import.meta.dirname, '..', 'worker', 'src', '_registry.ts')

const slugs: string[] = []

for (const entry of fs.readdirSync(agentsDir, { withFileTypes: true })) {
  if (!entry.isDirectory() || entry.name.startsWith('_')) continue
  const configPath = path.join(agentsDir, entry.name, 'agent.config.ts')
  if (fs.existsSync(configPath)) {
    slugs.push(entry.name)
  }
}

const imports: string[] = []
const registryEntries: string[] = []

for (const slug of slugs) {
  const varName = slug.replace(/-/g, '_')
  imports.push(`import ${varName}Config from '../../agents/${slug}/agent.config'`)

  // Scan tools directory
  const toolsDir = path.join(agentsDir, slug, 'tools')
  const toolImports: string[] = []
  const toolMap: string[] = []

  if (fs.existsSync(toolsDir)) {
    for (const file of fs.readdirSync(toolsDir)) {
      if (!file.endsWith('.ts')) continue
      const toolVarName = `${varName}_${file.replace(/[-\.]/g, '_').replace(/_ts$/, '')}`
      const toolPath = `../../agents/${slug}/tools/${file.replace('.ts', '')}`
      toolImports.push(`import ${toolVarName} from '${toolPath}'`)
      toolMap.push(`[${toolVarName}.id, ${toolVarName}]`)
    }
  }

  imports.push(...toolImports)
  registryEntries.push(
    `  ['${slug}', {\n    config: ${varName}Config,\n    tools: new Map([${toolMap.join(', ')}]),\n  }]`,
  )
}

const output = `// AUTO-GENERATED by scripts/build-registry.ts — do not edit
import type { AgentConfig } from '../../shared/types/agent'
import type { ToolDefinition } from '../../shared/types/tool'

${imports.join('\n')}

export interface AgentEntry {
  config: AgentConfig
  tools: Map<string, ToolDefinition>
}

export const agentRegistry = new Map<string, AgentEntry>([
${registryEntries.join(',\n')},
])
`

fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, output, 'utf-8')
console.log(`Registry generated: ${slugs.length} agent(s) → ${outFile}`)
