// AUTO-GENERATED by scripts/build-registry.ts — do not edit
import type { AgentConfig } from '../../shared/types/agent'
import type { ToolDefinition } from '../../shared/types/tool'

import bountyConfig from '../../agents/bounty/agent.config'
import bounty_get_contact from '../../agents/bounty/tools/get-contact'
import bounty_get_experience from '../../agents/bounty/tools/get-experience'
import bounty_get_skills from '../../agents/bounty/tools/get-skills'
import bounty_search_projects from '../../agents/bounty/tools/search-projects'

export interface AgentEntry {
  config: AgentConfig
  tools: Map<string, ToolDefinition>
}

export const agentRegistry = new Map<string, AgentEntry>([
  ['bounty', {
    config: bountyConfig,
    tools: new Map([[bounty_get_contact.id, bounty_get_contact], [bounty_get_experience.id, bounty_get_experience], [bounty_get_skills.id, bounty_get_skills], [bounty_search_projects.id, bounty_search_projects]]),
  }],
])
